rpm: remove ancient defines
Remove ancient commented out defines as they cause a build failure
when compiling on Mandriva_2009

error: /usr/src/rpm/SOURCES/vanessa_logger.spec:4: #%define is forbidden, use #define to comment a %define

Signed-off-by: Simon Horman <horms@verge.net.au>